-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 15:43:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_development_qrcode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_development_qrcode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_development_qrcode` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema database_production_qrcode
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_test_qrcode
-- -----------------------------------------------------
USE `database_development_qrcode` ;

-- -----------------------------------------------------
-- Table `database_development_qrcode`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_development_qrcode`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `database_development_qrcode`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_development_qrcode`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personFirstname` VARCHAR(255) NOT NULL,
  `personLastname` VARCHAR(255) NOT NULL,
  `personAdress` VARCHAR(255) NOT NULL,
  `personZipcode` VARCHAR(255) NOT NULL,
  `personCity` VARCHAR(255) NOT NULL,
  `personProblem` VARCHAR(255) NOT NULL,
  `personAge` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zipcode` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `phone1` VARCHAR(255) NOT NULL,
  `phone2` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
